# Generated by Django 2.0.9 on 2019-01-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDay',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='courseHourStart',
            field=models.IntegerField(choices=[(0, '9.00'), (1, '10.00'), (2, '11.00'), (3, '12.00'), (4, '13.00'), (5, '14.00'), (6, '15.00'), (7, '16.00')], default=None),
        ),
    ]
